root = "."

[build]
pre_cmd = ["templ generate components/*.templ"]
cmd = "go build -o out/cmd/server cmd/*.go"

bin = "out/cmd/server"

include_ext = ["go", "templ"]
exclude_dir = ["assets", "components"]

log = "air.log"
stop_on_error = true

[log]
time = false
main_only = false


[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
